/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
//import static model.CorridaDeSapos.NUM_SAPOS;

/**
 *
 * @author JohnPeter
 */
public class Corrida extends javax.swing.JFrame {
    
    final static int DISTANCIA = 500; // Distância da corrida em m    
    public static int panteraY, ironManY, hulkY, capitaoY, spiderY;    
    public static String panteraC, ironManC, hulkC, capitaoC, spiderC;    
    public static String panteraP, ironManP, hulkP, capitaoP, spiderP;    
    Thread pantera , ironMan, hulk, capitao, spider;   

    /**
     * Creates new form Corrida
     */
    public Corrida() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbPantera = new javax.swing.JLabel();
        lbIronMan = new javax.swing.JLabel();
        lbHulk = new javax.swing.JLabel();
        lbCapitao = new javax.swing.JLabel();
        lbSpider = new javax.swing.JLabel();
        btStart = new javax.swing.JButton();
        lbColocacaoHulk = new javax.swing.JLabel();
        lbColocacaoPantera = new javax.swing.JLabel();
        lbColocacaoSpider = new javax.swing.JLabel();
        lbColocacaoIronMan = new javax.swing.JLabel();
        lbColocacaoCapitao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbPassoPantera = new javax.swing.JLabel();
        lbPassoIronMan = new javax.swing.JLabel();
        lbPassoHulk = new javax.swing.JLabel();
        lbPassoCapitao = new javax.swing.JLabel();
        lbPassoSpider = new javax.swing.JLabel();
        btStop = new javax.swing.JButton();
        btResume = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Pista = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Corrida de Personagens");
        setBackground(new java.awt.Color(204, 255, 204));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        lbPantera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Black_Panther_(Civil_War)_featured.png"))); // NOI18N

        lbIronMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Comics-Ironman-Flying-icon.png"))); // NOI18N

        lbHulk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/The-Incredible-Hulk-2-icon.png"))); // NOI18N

        lbCapitao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/captain_america5.png"))); // NOI18N

        lbSpider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spiderman.png"))); // NOI18N

        btStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/forward-8-icon.png"))); // NOI18N
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        lbColocacaoHulk.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbColocacaoHulk.setForeground(new java.awt.Color(255, 102, 0));
        lbColocacaoHulk.setText("3");

        lbColocacaoPantera.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbColocacaoPantera.setForeground(new java.awt.Color(255, 102, 0));
        lbColocacaoPantera.setText("1");

        lbColocacaoSpider.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbColocacaoSpider.setForeground(new java.awt.Color(255, 102, 0));
        lbColocacaoSpider.setText("5");

        lbColocacaoIronMan.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbColocacaoIronMan.setForeground(new java.awt.Color(255, 102, 0));
        lbColocacaoIronMan.setText("2");

        lbColocacaoCapitao.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbColocacaoCapitao.setForeground(new java.awt.Color(255, 102, 0));
        lbColocacaoCapitao.setText("4");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PANTERA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("IRON MAN:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HULK:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CAPITÃO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HOMEM-");

        lbPassoPantera.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPassoPantera.setForeground(new java.awt.Color(255, 102, 0));
        lbPassoPantera.setText("         ");

        lbPassoIronMan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPassoIronMan.setForeground(new java.awt.Color(255, 102, 0));
        lbPassoIronMan.setText("        ");

        lbPassoHulk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPassoHulk.setForeground(new java.awt.Color(255, 102, 0));
        lbPassoHulk.setText("         ");

        lbPassoCapitao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPassoCapitao.setForeground(new java.awt.Color(255, 102, 0));
        lbPassoCapitao.setText("        ");

        lbPassoSpider.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPassoSpider.setForeground(new java.awt.Color(255, 102, 0));
        lbPassoSpider.setText("         ");

        btStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pause-icon.png"))); // NOI18N
        btStop.setEnabled(false);
        btStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStopActionPerformed(evt);
            }
        });

        btResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-edit-undo-icon.png"))); // NOI18N
        btResume.setEnabled(false);
        btResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResumeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NEGRA:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ARANHA:");

        Pista.setBackground(new java.awt.Color(153, 153, 153));
        Pista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PistaLayout = new javax.swing.GroupLayout(Pista);
        Pista.setLayout(PistaLayout);
        PistaLayout.setHorizontalGroup(
            PistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PistaLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        PistaLayout.setVerticalGroup(
            PistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbPantera)
                        .addGap(38, 38, 38)
                        .addComponent(lbIronMan)
                        .addGap(35, 35, 35)
                        .addComponent(lbHulk)
                        .addGap(38, 38, 38)
                        .addComponent(lbCapitao)
                        .addGap(33, 33, 33)
                        .addComponent(lbSpider)
                        .addGap(28, 28, 28)
                        .addComponent(btStart))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPassoPantera, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lbPassoIronMan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(lbPassoHulk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(lbPassoCapitao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPassoSpider, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lbColocacaoPantera, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(lbColocacaoIronMan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(lbColocacaoHulk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(lbColocacaoCapitao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(lbColocacaoSpider, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Pista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btResume)
                            .addComponent(btStop))))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPantera)
                    .addComponent(lbIronMan)
                    .addComponent(lbHulk)
                    .addComponent(lbCapitao)
                    .addComponent(lbSpider)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btStart, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbPassoPantera))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btStop)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btResume))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPassoIronMan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPassoHulk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPassoCapitao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(lbPassoSpider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbColocacaoPantera)
                    .addComponent(lbColocacaoIronMan)
                    .addComponent(lbColocacaoHulk)
                    .addComponent(lbColocacaoCapitao)
                    .addComponent(lbColocacaoSpider)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(709, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        pantera = new PersonagemCorrendoThread("Pantera", DISTANCIA, 0, 0);        
        ironMan = new PersonagemCorrendoThread("IronMan", DISTANCIA, 0, 0);
        hulk = new PersonagemCorrendoThread("Hulk", DISTANCIA, 0, 0);
        capitao = new PersonagemCorrendoThread("Capitao", DISTANCIA, 0, 0);
        spider = new PersonagemCorrendoThread("Spider", DISTANCIA, 0, 0);
        
        zerarStart();        
               
        pantera.start();
        ironMan.start();
        hulk.start();
        capitao.start();
        spider.start();        
                
        new Thread(){
            @Override
            public void run(){
                while(true){
                    atualizaPosicaoY();                    
                    atualizaColocacao();                     
                    atualizaQuantidadePassos();
                    
                    if(panteraY >= 500 && ironManY >= 500 && hulkY >= 500 && capitaoY >= 500 && spiderY >= 500){
                        btStart.setEnabled(true);
                        btResume.setEnabled(false);
                        btStop.setEnabled(false);
                    }
                    
                    try{
                        sleep(1);
                    }catch(InterruptedException ie){
                        ie.printStackTrace();
                    }
                }
            }
        }.start();
        btStart.setEnabled(false);
        btStop.setEnabled(true);
    }//GEN-LAST:event_btStartActionPerformed

    private void atualizaQuantidadePassos() {
        lbPassoPantera.setText(panteraP);
        lbPassoIronMan.setText(ironManP);
        lbPassoHulk.setText(hulkP);
        lbPassoCapitao.setText(capitaoP);
        lbPassoSpider.setText(spiderP);
    }

    private void atualizaColocacao() {
        lbColocacaoPantera.setText(panteraC);
        lbColocacaoIronMan.setText(ironManC);
        lbColocacaoHulk.setText(hulkC);
        lbColocacaoCapitao.setText(capitaoC);
        lbColocacaoSpider.setText(spiderC);
    }

    private void atualizaPosicaoY() {
        lbPantera.setLocation(100, panteraY);
        lbIronMan.setLocation(200, ironManY);
        lbHulk.setLocation(300, hulkY);
        lbCapitao.setLocation(400, capitaoY);
        lbSpider.setLocation(500, spiderY);
    }

    private void zerarStart() {
        panteraC = "";
        ironManC = "";
        hulkC = "";
        capitaoC = "";
        spiderC = "";
        
        panteraP = "";
        ironManP = "";
        hulkP = "";
        capitaoP = "";
        spiderP = "";
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon("src\\img\\Cinema-Avengers-icon.png").getImage());
    }//GEN-LAST:event_formWindowOpened

    private void btStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStopActionPerformed
        pantera.suspend();
        ironMan.suspend();
        hulk.suspend();
        capitao.suspend();
        spider.suspend();     
        btStop.setEnabled(false);
        btResume.setEnabled(true);
    }//GEN-LAST:event_btStopActionPerformed

    private void btResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResumeActionPerformed
        pantera.resume();
        ironMan.resume();
        hulk.resume();
        capitao.resume();
        spider.resume();
        btResume.setEnabled(false);
        btStop.setEnabled(true);
    }//GEN-LAST:event_btResumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corrida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pista;
    private javax.swing.JButton btResume;
    private javax.swing.JButton btStart;
    private javax.swing.JButton btStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbCapitao;
    private javax.swing.JLabel lbColocacaoCapitao;
    private javax.swing.JLabel lbColocacaoHulk;
    private javax.swing.JLabel lbColocacaoIronMan;
    private javax.swing.JLabel lbColocacaoPantera;
    private javax.swing.JLabel lbColocacaoSpider;
    private javax.swing.JLabel lbHulk;
    private javax.swing.JLabel lbIronMan;
    private javax.swing.JLabel lbPantera;
    private javax.swing.JLabel lbPassoCapitao;
    private javax.swing.JLabel lbPassoHulk;
    private javax.swing.JLabel lbPassoIronMan;
    private javax.swing.JLabel lbPassoPantera;
    private javax.swing.JLabel lbPassoSpider;
    private javax.swing.JLabel lbSpider;
    // End of variables declaration//GEN-END:variables
}
